@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle uml1

[Pump]
[Water Reservoir]
[Drain]

package "Feather" {
   node "GPIO Pins" {
    [D5]
    [D6]
    [D12]
   }
    node "Python main program"{
       [pumping_controller]
       node "Python Classes" {
       [remote_event_notifier]
       [http_functions]
       [pump_controller]
       [water_level]
       }
    }
  [pump_controller] -up-> [D12]:On/Off\nPower
  [water_level] <--up- [D5]:"Wet/Dry\nReading"
  [water_level] <--up- [D6]:"Wet/Dry\nReading"
}

package "Spring Boot\nRest Server" {
  [SpringBoot Java Application]
}


database "Physical Switch/Sensors" {
   [D12]--> [Relay Switch]:Wired
   [Relay Switch]--> [Pump]:Wired
   [D6] <-- [Top Water Sensor]:Wired
   [D5] <-- [Bottom Water Sensor]:Wired
}

[pumping_controller] <--> [remote_event_notifier]
[pumping_controller] --> [pump_controller]:Programmatic\nOn/Off
[pumping_controller] <-- [water_level]:Programmatic\nDry/Wet

[external_water_source]  --> [Water Reservoir]:Tubing

[remote_event_notifier] <--down-> [http_functions]
[http_functions] <--down-> [SpringBoot Java Application]:HTTP POST/GET
[Top Water Sensor] <--down- [Water Reservoir]:Sensor\nPhysically\nInside\nReservoir
[Bottom Water Sensor] <-down- [Water Reservoir]:Sensor\nPhysically\nInside\nReservoir
[Water Reservoir] --down-> [Pump]:Tubing
[Pump] ---> [Drain]:Tubing
@enduml